# {{ cookiecutter.project_name }} - Full Site Setup Playbook
# Run: ansible-playbook -i inventory/production.yml playbooks/site.yml
---
- name: Setup {{ cookiecutter.project_name }} Server
  hosts: all
  become: yes
  
  roles:
    - common
    - docker
    - traefik
    - postgres
    - redis
    - app
    - backup
  
  post_tasks:
    - name: Display deployment info
      debug:
        msg: |
          âœ… {{ cookiecutter.project_name }} deployed successfully!
          
          ğŸŒ Application: https://{{ app_domain }}
          ğŸ“Š Traefik Dashboard: http://{{ ansible_host }}:8080 (staging only)
          
          ğŸ“ Project home: {{ project_home }}
          ğŸ‘¤ User: {{ project_user }}
